name: Hot Tub Reservation
description: Reserve a hot tub today!
title: "Reservation Request: Hot Tub"
labels: ["request"]
assignees: [peckjon]
body:
  - type: input
    id: name
    attributes:
      label: Your Name
    validations:
      required: true
  - type: input
    id: phone
    attributes:
      label: Phone number (used for questions and for day-of contact)
      placeholder: 206-555-1212
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Email (used for reservation details and payment)
      placeholder: email@example.com
    validations:
      required: true
  - type: dropdown
    id: size
    attributes:
      label: Hot Tub Size
      #description:
      options:
        - "Small (2-4 people): $100/day, $300/wk"
        - "Medium (4-8 people): $125/day, $375/wk"
        - "Large (-12 people): $150/day, $450/wk"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Outside delivery and pickup is included with all hot tub rentals. An adult (18+) must be present during dropoff and pickup. Tub is delivered uninflated and unfilled, and must be returned drained, deflated, and folded.
  - type: checkboxes
    id: addon
    attributes:
      label: Add-ons
      description: "Optional upgrades:"
      options:
        - label: "Set it up for me: a technician will set up and fill the tub (+$25)"
        - label: "Break it down for me: a technician will drain and re-pack the tub (+$25)"
        - label: "Inside delivery and pickup: not more than 2 flights of stairs (+$25)"
  - type: textarea
    id: info
    attributes:
      label: Reservation details
      description: Is there anything specific we should know about the location or event?
      #placeholder:
      #value:
      #render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Reservation Policies
      description: I have reviewed and agree to follow the [reservation policies](README.md)
      options:
        - label: An adult (18+) will be present for dropoff an pickup
          required: true
        - label: A clean water source and drainage area (lawn or drain) will be made available
          required: true
        - label: The installation area is water-safe; the company is not responsible for any water damage
          required: true
        - label: I am responsible for the safety of all gests allowed in or near the hot tub
          required: true
        - label: I will not allow the hot tub to be used by anyone who is drunk/intoxicated, under the age of 12, or unable to swim
          required: true
        - label: I will be held liable for any damage to the hot tub up to $2000, held on my payment method, and will keep glass and sharp objects away from the tub
          required: true
